### ISSUE TITLE
Metamask mobile app doesn't show confirmation when transaction completed. Also no error message when failed.

### ISSUE THREAD

**Issue by johannesmols** [johannesmols/ethVote-react#1]
This might just be a bug in the mobile app, as it works perfectly in Chrome and Firefox.

**Comment by johannesmols** [comment]
https://github.com/MetaMask/metamask-mobile/issues/1111

**Comment by benjaminaaron** [comment]
You can use `chrome://inspect/#devices` to see the tab opened in MetaMask on your Android phone plus the console loggings. Your phone has to be connected via USB debugging to the computer.
